name: build and run tests
on: [ push, pull_request ]

jobs:
  build:
    env:
      DB_USER: steve
      DB_PASSWORD: changeme
      DB_SCHEMA: stevedb_test_2aa6a783d47d
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
        java: [ '11', '17' ]
        db: [ 'mysql:5.7', 'mysql:8.0', 'mariadb:10.3', 'mariadb:10.4.30', 'mariadb:10.5.21', 'mariadb:10.6.14' ]
    runs-on: ${{ matrix.os }}
    services:
      mysql:
        image: ${{ matrix.db }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17 for build
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Set up MySQL for tests
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "SELECT @@VERSION;"
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "CREATE DATABASE $DB_SCHEMA;" -v
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';" -v
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "GRANT ALL PRIVILEGES ON $DB_SCHEMA.* TO '$DB_USER'@'%';" -v
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "GRANT SELECT ON mysql.proc TO '$DB_USER'@'%';" -v || true
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "GRANT SUPER ON *.* TO '$DB_USER'@'%';" -v || true

      - name: Build with Maven
        run: ./mvnw -B -V -Dmaven.javadoc.skip=true -Ddb.user=$DB_USER -Ddb.password=$DB_PASSWORD -Ddb.schema=$DB_SCHEMA -Ptest clean package --file pom.xml

      - name: Set up Java ${{ matrix.Java }} for run
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Start the app and visit signin web page
        run: |
          sudo apt-get install -y elinks
          java -Djava.net.preferIPv4Stack=true -jar target/steve.jar &
          sleep 30
          elinks -dump -no-references http://localhost:8080/steve/manager/signin
          killall java
